added controller
lizzymikhailovskaia/capstone pull request #1
Opened 2017-02-27 07:44 UTC by lizzymikhailovskaia

2017-02-28 02:29 UTC, vovanmix commented on app/models/location.rb
> +  has_many :photos
Has many comments as well?

2017-02-28 02:30 UTC, lizzymikhailovskaia commented
Why?

On Mon, Feb 27, 2017 at 6:29 PM, Vladimir Mikhaylovskiy <
notifications@github.com> wrote:

> *@vovanmix* commented on this pull request.
> ------------------------------
>
> In app/models/location.rb
> <https://github.com/lizzymikhailovskaia/capstone/pull/1#discussion_r103363962>
> :
>
> > @@ -0,0 +1,5 @@
> +class Location < ActiveRecord::Base
> +  belongs_to :trip
> +  has_many :tasks
> +  has_many :photos
>
> Has many comments as well?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lizzymikhailovskaia/capstone/pull/1#pullrequestreview-24147262>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AWW6BZqg0LhLmeRlvYDJ5jottV8DwOvJks5rg4ZygaJpZM4MMyaN>
> .
>

2017-02-28 03:03 UTC, vovanmix requested changes
Good, but need to add some more associations

2017-03-02 04:07 UTC, merged

2017-03-02 04:14 UTC, lizzymikhailovskaia commented on app/models/location.rb
> +  has_many :photos
added

2017-03-02 04:15 UTC, lizzymikhailovskaia commented on app/models/location.rb
> +  has_many :photos
'class Location < ActiveRecord::Base
  belongs_to :trip
  has_many :tasks
  has_many :photos
  has_many :comments
end
'

>

2017-03-02 04:27 UTC, lizzymikhailovskaia commented
LGTM 👍

2017-03-02 04:27 UTC, lizzymikhailovskaia commented
looks good to me